t1=input("Enter your colour: ")
t2=input("Enter another colour: ")
t3=input("Enter your name: ")
print("Roses are " +t1)
print(t2+ " are blue")
print("be mine " +t3)
print("i give your shoe ")
